package com.yurastico.pingpongx

class Constants {
}
const val KEY_RESULT_EXTRA_PLAYER_ONE_NAME = "KEY_RESULT_EXTRA_PLAYER_ONE_NAME"

const val KEY_RESULT_EXTRA_PLAYER_TWO_NAME = "KEY_RESULT_EXTRA_PLAYER_TWO_NAME"

const val KEY_RESULT_EXTRA_PLAYER_ONE_SCORE = "KEY_RESULT_EXTRA_PLAYER_ONE_SCORE"

const val KEY_RESULT_EXTRA_PLAYER_TWO_SCORE = "KEY_RESULT_EXTRA_PLAYER_TWO_SCORE"

